### ISSUE TITLE
Error with 'querySelector' usage

### ISSUE THREAD

**Issue by pawan-live** [itsvihanga/project-no2#2]
There's an error with how you're using document.querySelector.

Change all the relevant HTML to look like this:

`<div class="hand hour" id="hour-hand"></div>`

and accordingly tweak the JS

`const hourHand = document.querySelector("#hour-hand");`

It works

**Comment by pawan-live** [comment]
suggestion: rename the repository to something interesting rather than 'project no2' :)

**Comment by itsvihanga** [comment]
solved
